server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000
